name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  merge_group:
    types: [checks_requested]


jobs:
  windows:
    runs-on: windows-2022
    steps:
      - run: |
          "$env:WIX\bin" >> $env:GITHUB_PATH
      - run: |
          Get-ChildItem Env: | Format-Table -Wrap -AutoSize
        shell: pwsh
      - run: candle

  build-result:
    name: Result
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Success
        if: ${{ !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') }}
        run: exit 0
      - name: Failure
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        run: exit 1

